name: test

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-20.04
    continue-on-error: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.16.0
          cache: 'npm'
      - run: npm install
      - run: npm run check-covers
      - run: npm run build
      - run: npm run lint
